version: 2
updates:
  - package-ecosystem: maven
    directory: "/java"
    schedule:
      interval: weekly
      day: "friday"
    assignees:
      - "javiertuya" 
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 20
    assignees:
      - "javiertuya" 